carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns= [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('', include('webApp.urls')),
]

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="tienda"),
]

tienda/models.py
from django.db import models

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProd'
        verbose_name_plural = 'CategoriasProd'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=20)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'  

carro/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .carro import Carro
from tienda.models import Producto

def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return redirect("tienda")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return redirect("tienda")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return redirect("tienda")

def limpiar_carro(request, producto_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto

def tienda(request):

    productos=Producto.objects.all()
    return render(request, "tienda/tienda.html", {"productos": productos})

tienda/templates/tienda/carro/widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
</head>
<body>
    <table class="table table-bordered" style="color:black; font-size: 12px; width: 100%; margin: 0 auto;">
        <thead>
            <tr>
                <th colspan="3" class="text-center" style="font-size: 14px;">
                    Carrito
                </th>
            </tr>
            <tr>
                <th>Prod.</th>
                <th>Cantidad</th>
                <th>Suma</th>
            </tr>
        </thead>

        <tbody>
            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}
                    <tr class="text-center">
                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        <td>
                            <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>

                            ${{value.precio}}

                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3" class="text-center">
                        <div class="alert alert-danger">
                            Sin productos
                        </div>
                    </td>
                </tr>
            {% endif %}
        </tbody>

        <tfoot>

           <tr>
                <td colspan="3">
                    total: $ {{importe_total_carro}}
                </td>
           </tr> 

           {% if request.session.carro.items %}
           <tr>
                <td colspan="3" style="text-align: center;">
                    <a href="#" class="btn btn-success"> Confirmar </a>
                </td>
           </tr>
           {% endif %}

        </tfoot>
    </table>
</body>

</html>